### ISSUE TITLE
backslash character

### ISSUE THREAD

**Issue by patatetom** [harelba/q#152] opened 2017-07-19 08:54 UTC
hi,
I have a tab separated values file that contains Windows paths that have backslash characters :
```bash
$ cat myfile.tsv
1    C:\Windows\file.1
2    C:\Windows\file.2
```
when I use q on it, backslash characters disappear :
```bash
$ q -t 'SELECT * FROM myfile.tsv'
1    C:Windowsfile.1
2    C:Windowsfile.2
```
I tried to play on the options -w and -W but nothing made.
regards, lacsaP.

**Comment by bitti** [comment] 2017-07-19 13:44
I cannot reproduce this. Can you provide the output of `cat -t myfile.tsv`, `q -t 'SELECT * FROM myfile.tsv'|cat -t` and `sqlite3 <<<.show`?

**Comment by stonedbovines** [comment] 2017-07-19 14:52
I can reproduce the same result as @patatetom on both linux (q 1.6.3) and windows (q 1.5.0).

I can get the backslashes by escaping them (double backslash) in myfile.tsv, when they then show up as single backslashes in the result.

**Comment by bitti** [comment] 2017-07-19 15:41
I see, I only tested with q 1.4.0. With q 1.6.0 I can reproduce the problem as well so it seems to be a regression.

**Comment by patatetom** [comment] 2017-07-19 19:22
some precisions :
```bash
$ cat -t myfile.tsv
1^IC:\Windows\file.1
2^IC:\Windows\file.2

$ q -v
q version 1.6.3
Copyright (C) 2012-2017 Harel Ben-Attia (harelba@gmail.com, @harelba on twitter)
http://harelba.github.io/q/

$ q -t 'SELECT * FROM myfile.tsv' | cat -t
1^IC:Windowsfile.1
2^IC:Windowsfile.2

$ sqlite3 <<<.show
        echo: off
         eqp: off
     explain: auto
     headers: off
        mode: list
   nullvalue: ""
      output: stdout
colseparator: "|"
rowseparator: "\n"
       stats: off
       width: 
    filename: :memory:
```

**Comment by cmprmsd** [comment] 2022-03-11 13:30
Did you find a workaround or fix for this issue?

**Comment by bitti** [comment] 2022-03-11 21:50
Maybe it's considered a feature not a bug? The only workaround I currently see is to double escape the backslashes:

```console
$ sed 's/\\/\\\\/g' myfile.tsv | q -t 'SELECT * FROM -'
1	C:\Windows\file.1
2	C:\Windows\file.2
```

**Comment by cmprmsd** [comment] 2022-03-11 21:57
As such things work in ui plugins such as rainbow csv for VSCode I'd consider it a bug. But your workaround seems legit 😇 
Thanks!

**Comment by harelba** [comment] 2022-03-12 12:15
Hi, 

By default, q treats backslashes as escape characters for double-quotes, mainly due to the fact that there are a lot of existing data files which using data. This it what causes the disappearance of them when they are meant to be used as a regular character.

q has a flag that can disable this capability, called `--disable-escaped-double-quoting`. You can run the command with it, and it will prevent this behaviour:

```
$ cat x.tsv
1	C:\Windows\file.1
2	C:\Windows\file.1
$ q -t "select * from x.tsv" --disable-escaped-double-quoting
1	C:\Windows\file.1
2	C:\Windows\file.1
$
```

Notice that if the data contains backslashes which are meant to be escaping-backslashes, then it might obviously not work well, as it means that the data file is not consistent.

Hope this helps,
Harel

btw, just to make sure people reading this are aware - The examples show q version `1.x`, and there's already a `3.1.6` version, with major additions and improvements. It also contains a revamped `~/.qrc`, which would easily allow you to set this flag as the default behaviour instead of adding it to every q command.

**Comment by harelba** [comment] 2022-03-12 12:21
@cmprmsd - A side-note regarding your comment about UI plugins supporting this - In general I would love q to be handle such cases automatically without having to add any flags. However, there's a difference between entering text in a UI (presentation), and storing it inside files (actual data). 

A UI plugin knows to differentiate between text (user-entered), and between the actual data (escaping it as needed behind the scenes). q has access only to the (encoded) data in the file, and that data has to be consistently encoded in order to know what exactly is the data. 

Unfortunately, delimited files have multiple standards which are not fully consistent, and the files do not contain any metadata about how the system which wrote the file encoded it, so it's harder to implement some generic decoding mechanism which will be able to read all files. This is one of the reasons that I've added multiple flags to q that can help with the proper decoding.

**Comment by cmprmsd** [comment] 2022-03-12 12:26
@harelba Thank you for pointing this out! You are right. 💪 I just did not match the argument name to this behavior. 
Maybe it would help to write a hint into the help function e.g.. (disables also \ escapes) 😁 

Great tool, thanks a lot!

**Comment by harelba** [comment] 2022-03-12 13:06
Thanks! Really glad you find it useful.

That's a great idea, i'll add it to the help text.

**Closed by harelba** 2022-03-12 13:06 UTC
