### ISSUE TITLE
Support too many files

### ISSUE THREAD

**Issue by peylight** [harelba/q#180] opened 2018-10-17 05:54 UTC
Hi
There are some problem in linux (i tested) if i have too many files this error will be happened:
`IOError: [Errno 24] Too many open files`
Also it is very slow and using just one core for processing...

**Comment by bitti** [comment] 2018-10-17 15:40
How is this `q` related? Can you give an example commandline which is triggering this?

**Comment by peylight** [comment] 2018-10-17 17:56
@bitti 
That error is about OS and python.
But it happened if there are too many input files. Like a wildcard for ex:
`q "SElECT COUNT(*) FROM ./path/to/myfiles_* WHERE c1 == 'sample'"`
I think `q` try to open all files in once and then the error will be happened

**Comment by bitti** [comment] 2018-10-18 06:17
Interesting, I didn't now `q` supports fileglobs. But that's probably because I usually would never use them and do an explicit cat instead. E.g. in your example

    cat ./path/to/myfiles_* | q "SELECT COUNT(*) FROM - WHERE c1 == 'sample'"

or

    q "SELECT COUNT(*) FROM "<(cat ./path/to/myfiles_*)" WHERE c1 == 'sample'"

I'm sure `cat` is smart enough to avoid opening all input files at once. Still maybe @harelba is able to optimize the supported glob?

**Comment by harelba** [comment] 2018-10-18 16:01
hi, yeah q supports glob, and actually also un-gzips `.gz` files provided to it as table names.

The bug itself is interesting, i'll definitely take a deeper look.

**Comment by harelba** [comment] 2018-10-19 07:35
Tried some stuff, this is odd, since it seems that q is handling the file closing properly. 

When you test @bitti 's variation, using `cat`, you don't get any error, right?

**Comment by harelba** [comment] 2018-11-17 23:02
@peylight would you mind adding the needed information? I'm gonna be releasing a new version soon, and I want to add an fixes for this bug as well if possible.

**Comment by harelba** [comment] 2018-12-07 09:59
@peylight kind reminder about this issue.

**Comment by peylight** [comment] 2018-12-07 17:20
@harelba 
By `cat` and then pipe into `q` it's working fine.
`$ ulimit -a`
`open files                      (-n) 1024`
So if you make more than 1024 files, it's will be happen.
I can't run another command when the error happening. it's very fast!

**Comment by peylight** [comment] 2018-12-07 17:20
@harelba 
By `cat` and then pipe into `q` it's working fine.
`$ ulimit -a`
`open files                      (-n) 1024`
So if you make more than 1024 files, it's will be happen.
I can't run another command when the error happening. it's very fast!

**Comment by harelba** [comment] 2018-12-08 12:14
@peylight Would be glad to get your exact command line, and some screen shot/output of the files in your folder

**Comment by peylight** [comment] 2018-12-08 19:33
Yea, I can give you the exact files and command.
[Download files](https://files.catbox.moe/8v6un9.zip)
Command: `q "SElECT COUNT(*) FROM q-test/* WHERE c1 == 'sample'"`

**Comment by harelba** [comment] 2018-12-10 13:57
thanks! indeed now i've managed to reproduce the problem, i did create lots of files, but i probably missed something in setting the file limit, since it wasn't reproduced earlier.

This happens because q opens the files in parallel, i'll take a deeper look to see how to optimize this so no one will get this error.

Thanks again

**Comment by harelba** [comment] 2021-01-15 14:41
Missed this ticket by accident. Reanalysed it, it's indeed a bug, small effort to fix. I'll integrate it into the next release.

**Comment by harelba** [comment] 2021-12-02 09:39
Next release is out. Many files are supported now.

**Closed by harelba** 2021-12-02 09:39 UTC
