### ISSUE TITLE
Unable to escape space in directory name

### ISSUE THREAD

**Issue by rolfen** [harelba/q#163] opened 2018-02-26 15:08 UTC
I'm trying to do this:

```
q 'select * from `./Big Fat Disk/hashes.complete.txt`'
```
I have tried every trick that I could think of, such as adding backspace before the space, enclosing the directory name in escaped double quotes, single quotes, etc. `Q` never gets past the first space:

```
No files matching '`./Big' have been found
```
This issue might be related: https://github.com/harelba/q/issues/4 

By the way, thanks for this software, pretty cool.

**Comment by rolfen** [comment] 2018-02-26 21:26
By the way, the documentation says that spaces should be supported:

> Please note that column names that include spaces need to be used in the query with back-ticks, as per the sqlite standard.

They are not, on latest master.

**Comment by harelba** [comment] 2018-03-03 09:38
Hi, sorry for the late reply.

Spaces are supposed only in column names with back-ticks, but you're right, this issue is the same as #4, spaces in table names and file names are not supported. There's no plan to add support for it now, as it's a relatively high effort for a use-case that can be easily worked-around in most cases (`cat "./Big Fat Disk/hashes.complete.txt" | q "select * from -"`)

I'll add this to the limitations, and close this as it's a duplicate of #4.

**Closed by harelba** 2018-03-03 09:38 UTC
